<?php

/**
 * @file
 * dataone_example.module
 */

define('DATAONE_EXAMPLE_TABLE_LOG', 'dataone_example_log');

/**
 * Implements hook_dataone_api_versions_alter().
 */
function dataone_example_dataone_api_versions_alter(&$versions) {
  // Implementing modules should use this hook to define their own API classes.
  $versions['v1']['class'] = 'ExampleDataOneApiVersionOne';
}

/**
 * Get a PID for a Drupal node.
 *
 * @param mixed $node
 *   A node or node ID
 *
 * @return mixed
 *   Either a string representing the PID or FALSE
 */
function dataone_example_get_pid($node) {
  // If a node ID, load the node.
  if (is_numeric($node)) {
    $node = node_load($node);
    // If the node doesn't exist, return FALSE.
    if (empty($node)) {
      return FALSE;
    }
  }
  // Send the node ID as the PID.
  return $node->nid;
}

/***** LOG FUNCTIONS for MNCore.getLogRecords() *****/

/**
 * Implements hook_dataone_event().
 */
function dataone_example_dataone_event($event_type, $pid = FALSE) {
  $ip_address = ip_address();
  $user_agent = _dataone_get_user_agent();
  _dataone_example_log_record($pid, $event_type, time(), $ip_address, $user_agent);
}

/**
 * Implements hook_node_insert().
 */
function dataone_example_node_insert($node) {
  $pid = dataone_example_get_pid($node);
  $ip_address = ip_address();
  $user_agent = _dataone_get_user_agent();
  _dataone_example_log_record($pid, 'create', $node->created, $ip_address, $user_agent);
}

/**
 * Implements hook_node_update().
 */
function dataone_example_node_update($node) {
  $pid = dataone_example_get_pid($node);
  $ip_address = ip_address();
  $user_agent = _dataone_get_user_agent();
  _dataone_example_log_record($pid, 'update', $node->changed, $ip_address, $user_agent);
}

/**
 * Implements hook_node_update().
 */
function dataone_example_node_delete($node) {
  $pid = dataone_example_get_pid($node);
  $ip_address = ip_address();
  $user_agent = _dataone_get_user_agent();
  _dataone_example_log_record($pid, 'delete', time(), $ip_address, $user_agent);
}

/**
 * Get the User-Agent for the current request.
 *
 * @return string
 *   The User-Agent value
 */
function _dataone_get_user_agent() {
  return !empty($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
}

/**
 * Save a log record.
 *
 * @param string $pid
 *   The PID
 *
 * @param string $event
 *   The event type
 *
 * @param int $timestamp
 *   The timestamp for the event, like time()
 *
 * @param string $ip_address
 *   The IP Address of the initiating request
 *
 * @param string $user_agent
 *   The User-Agent request header of the initiating request
 *
 * @return int
 *   The entry_id value, the primary key of the log record
 */
function _dataone_example_log_record($pid, $event, $timestamp, $ip_address = '', $user_agent = '') {
  $log_record = array(
    'pid' => $pid,
    'event' => $event,
    'timestamp' => $timestamp,
    'ip_address' => $ip_address,
    'user_agent' => $user_agent,
  );
  return db_insert(DATAONE_EXAMPLE_TABLE_LOG)->fields($log_record)->execute();
}
